# Generated by Django 4.1.3 on 2022-12-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovarnomi', models.CharField(max_length=100, verbose_name='Tovar nomi')),
                ('tovarnarxi', models.CharField(max_length=100, verbose_name='Tovar narxi')),
                ('tovarsoni', models.CharField(max_length=100, verbose_name='TOvar soni')),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Sklad',
            },
        ),
    ]
