# Generated by Django 4.1.3 on 2022-12-07 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmanomi', models.CharField(max_length=200)),
                ('tovarnomi', models.CharField(max_length=200)),
                ('tovarolishnarxi', models.CharField(max_length=200)),
                ('tovarsotishnarxi', models.CharField(max_length=200)),
                ('tovarsoni', models.CharField(max_length=200)),
                ('jamitovarnarxi', models.CharField(max_length=200)),
                ('olingansana', models.CharField(max_length=100)),
                ('berilganpul', models.CharField(max_length=100)),
                ('qarz', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 22, 1, 42, 440046))),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'Olingan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xaridornomi', models.CharField(max_length=100)),
                ('tovarnomi', models.CharField(max_length=100)),
                ('berganpuli', models.CharField(max_length=100)),
                ('qolganqariz', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 22, 1, 42, 441043))),
            ],
        ),
        migrations.CreateModel(
            name='Qaytarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xaridornomi', models.CharField(max_length=200)),
                ('tovarnomi', models.CharField(max_length=200)),
                ('tovarnarxi', models.CharField(max_length=200)),
                ('tovarsoni', models.CharField(max_length=200)),
                ('jamitovarnarxi', models.CharField(max_length=200)),
                ('sana', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 22, 1, 42, 441043))),
            ],
        ),
        migrations.CreateModel(
            name='Sotish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xaridornomi', models.CharField(max_length=200)),
                ('tovarnomi', models.CharField(max_length=200)),
                ('tovarnarxi', models.CharField(max_length=200)),
                ('tovarsoni', models.CharField(max_length=200)),
                ('jamitovarnarxi', models.CharField(max_length=200)),
                ('sotilgansana', models.CharField(max_length=100)),
                ('berilganpul', models.CharField(max_length=100)),
                ('qarz', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 22, 1, 42, 438913))),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'Sotilgan mahsulotlar',
            },
        ),
        migrations.AlterField(
            model_name='sklad',
            name='tovarsoni',
            field=models.CharField(max_length=100, verbose_name='Tovar soni'),
        ),
    ]
